#pragma once

#define HLT_DEBUG_PRINT 0
#define HLT_DEBUG_TIME 0

#define DEBUG_TIME_SUM_DIAGONAL 2
#define HLT_DEBUG_FLAG 3
#define DEBUG_TIME_ONE_DIAGONAL 4
#define DEBUG_TIME_DEC 5
#define DEBUG_TIME_DEC_NTT 6
